### ISSUE TITLE
"New Search" button should say "Search this artist"

### ISSUE THREAD

**Issue by mikesigs** [dvrylc/discoversounds#1]
The New Search button text is a bit misleading. At first I thought it was going to clear the search results and focus the text input at the top, but instead it search for results of the selected artist. Hence, "Search this artist" much more clearly explains the intent of the button's action.

**Comment by dvrylc** [comment]
Fixed fe55e9dc453fa0b095e83ed1117ca6420878d20c, thanks!

**Comment by mikesigs** [comment]
Much clearer, thanks!
