### ISSUE TITLE
Normalize search terms

### ISSUE THREAD

**Issue by mikesigs** [dvrylc/discoversounds#2]
Searching for a band with punctuation in its name shows different results when you search with and without that punctuation, e.g. "Victim's Family" and "Victims Family". 

No results are returned when searching for a band whose name starts with "The" but you forget the "The", e.g. "Velvet Underground" shows no results, but "The Velvet Underground" does.

One good way to fix this might be to add some typeahead/auto-suggest when entering a band name.

**Comment by dvrylc** [comment]
After some debugging, I found that Spotify's library has both "Victim's Family" and "Victims Family" as artists with different related artists. Kinda weird but probably a one-off thing. 

As for the search field, the search works based on the exact text that's entered in the field. If it can't find an artist that matches the entered text, it returns the "artist that you entered was not found" message. For example, the official artist name is "The Velvet Underground" and so "Velvet Underground" returns no results. 

I agree that typeahead will solve this problem and I'm looking into it. Thanks for the suggestions!
