### ISSUE TITLE
Not clear which artist your results are for

### ISSUE THREAD

**Issue by mikesigs** [dvrylc/discoversounds#3]
If I put in "Clash" I get results, but "The Clash" shows a different set of results. Similarly searching for "Rage" and "Rage Against the Machine" show different results. I don't even know if there's a band called "Rage". I suppose it's possible. But I have no way of knowing which band my search has actually identified as the band I wanted to search. All I see are the results. It would be nice to show on the UI that band that the search is targeting based on my terms. As mentioned in a different issue, having some typeahead/auto-suggest would help too.

**Comment by dvrylc** [comment]
As explained in the response to issue #2, the search works based on the official exact name of the artist. In the examples you raised, "Clash" and "The Clash" are two different artists, and so are "Rage" and "Rage Against the Machine". 

Hope this clears it up, I'll look into the typeahead feature that you mentioned. Thanks!

**Comment by mikesigs** [comment]
Would still be nice to show something like: "Showing results for: **System of a Down"**"
