### ISSUE TITLE
Larger buttons

### ISSUE THREAD

**Issue by mikesigs** [dvrylc/discoversounds#4]
The buttons are very small and hard to get your mouse precisely into. Enlarging the buttons would also help on mobile devices. Add some white-space around them too!

**Comment by dvrylc** [comment]
Added margins in fe55e9dc453fa0b095e83ed1117ca6420878d20c around the buttons to make them more mobile-friendly but larger icons looked a little unsightly so I'm keeping them at them same size.

**Comment by mikesigs** [comment]
The margin looks nice indeed.
